#!/bin/bash
rm -rf ~/app
mkdir ~/app  
git clone https://github.com/dorna-robotics/firmware.git ~/app
cd ~/app
tar -xvf FW.tar.gz
python3 Unlock_Flash.py
python3 Firmware_Upgrade.py
python3 Lock_Flash.py
rm efirmware
rm FW.tar.gz